baseURL: "https://blog.joaograssi.com"
languageCode: "en-us"
title: "Joao Grassi's blog"
paginate: 5
theme: hugo-PaperMod

enableEmoji: true
enableInlineShortcodes: true
enableRobotsTXT: true

outputFormats:
  RSS:
    mediatype: "application/rss+xml"
    baseName: "rss"

# In order to avoid need the extension on the rss feed
mediaTypes:
    application/rss+xml:
      suffixes: []

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archives
          url: /archives/
          weight: 1
        - name: Tags
          url: /tags/
          weight: 2
        - name: Series
          url: /series/
          weight: 3
        - name: Privacy policy
          url: /privacy-policy
          weight: 4

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  description: "My errands in software development. Mostly .NET stuff, with a bit of front-end here and there."
  author: Joao
  ShowReadingTime: true
  defaultTheme: auto
  ShowShareButtons: false
  displayFullLangName: true
  ShowCodeCopyButtons: true
  cover:
      responsiveImages: false
  homeInfoParams:
        Title: Joao Grassi's Blog
        Content: My errands in software development. Mostly .NET stuff, with a bit of front-end here and there.
  socialIcons:
        - name: "twitter"
          url: "https://twitter.com/jotagrassi"
        - name: "github"
          url: "https://github.com/joaopgrassi"
        - name: "stackoverflow"
          url: "https://stackoverflow.com/users/2689390/jpgrassi"
        - name: "keybase"
          url: "https://keybase.io/joaopgrassi"
        - name: "rss"
          url: "rss"

taxonomies:
  category: categories
  tag: tags
  series: series

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
